const usuario = require("./usuario.routes");
const questao = require("./questao.routes");
const hardskill = require("./hardskill.routes");
const alunoHardskills = require("./aluno_hardskills.routes");
const alunoGrupo = require("./aluno_grupo.routes");
const alunoSoftskill = require("./aluno_softskill.routes");
const alunoTurma = require("./aluno_turma.routes");
const aluno = require("./aluno.routes");
const atividadeHardskill = require("./atividade_hardskill.routes");
const atividade = require("./atividade.routes");
const avaliacao360Softskill = require("./avaliacao360_softskill.routes");
const avaliacao360 = require("./avaliacao360.routes");
const cursoTurma = require("./curso_turma.routes");
const curso = require("./curso.routes");
const disciplinaHardskill = require("./disciplina_hardskill.routes");
const disciplina = require("./disciplina.routes");
const grupo = require("./grupo.routes");
const professorDisciplina = require("./professor_disciplina.routes");
const professorTurma = require("./professor_turma.routes");
const professor = require("./professor.routes");
const questaoDia = require("./questaodia.routes");
const softskill = require("./softskill.routes");
const tarefa = require("./tarefa.routes");
const turmaHardskill = require("./turma_hardskill.routes");
const turma = require("./turma.routes");

module.exports = (app) => {
  app.use("/api/usuario", usuario);
  app.use("/api/questao", questao);
  app.use("/api/hardskill", hardskill);
  app.use("/api/aluno_hardskills", alunoHardskills);
  app.use("/api/aluno_grupo", alunoGrupo);
  app.use("/api/aluno_softskill", alunoSoftskill);
  app.use("/api/aluno_turma", alunoTurma);
  app.use("/api/aluno", aluno);
  app.use("/api/atividade_hardskill", atividadeHardskill);
  app.use("/api/atividade", atividade);
  app.use("/api/avaliacao360_softskill", avaliacao360Softskill);
  app.use("/api/avaliacao360", avaliacao360);
  app.use("/api/curso_turma", cursoTurma);
  app.use("/api/curso", curso);
  app.use("/api/disciplina_hardskill", disciplinaHardskill);
  app.use("/api/disciplina", disciplina);
  app.use("/api/grupo", grupo);
  app.use("/api/professor_disciplina", professorDisciplina);
  app.use("/api/professor_turma", professorTurma);
  app.use("/api/professor", professor);
  app.use("/api/questaoDia", questaoDia);
  app.use("/api/softskill", softskill);
  app.use("/api/tarefa", tarefa);
  app.use("/api/turma_hardskill", turmaHardskill);
  app.use("/api/turma", turma);
};
